Dictionary = {

'Internal Medicine':'内科',
'Comprehensive Internal Medicine':'総合内科',	
'Rheumatology':'リウマチ科',
'Pulmonology':'呼吸器科',
'Respiratory Medicine':'呼吸器内科',
'Hematology':'血液内科',	
'Neurology':'神経科',	
'Cardiology':'循環器内科',	
'Gastroenterology':'消化器内科',	
'Gastrointestinal':'胃腸科',
'Nephrology':'腎臓内科',
'Hepatology':'肝臓内科',
'Endocrinology':'内分泌内科',	
'Hepatobiliary':'肝胆膵内科',	
'Pancreatic':'肝胆膵内科',
'Otorhinolaryngology':'耳鼻咽喉科',	
'Geriatrics':'老年内科'	,
'Neonatology':'新生児科',
'Pediatrics':'小児科',
'Infectious Diseases':'感染症科',
'Dermatology':'皮膚科',	
'Ophthalmology':'眼科',	
'Obstetrics and Gynecology':'産婦人科',	
'Gynecology':'婦人科',
'Oral Medicine':'口腔内科',	
'Dentistry':'歯科',
'Radiology':'放射線',
'Diagnostic Radiology':'放射線診断科',	
'Radiation Oncology':'放射線治療科',
'Oncology':'腫瘍内科',	
'Chemotherapy':'化学療法部',	
'Pathology':'病理診断科',
'Diagnostic Pathology':'病理診断科',	
'Laboratory Medicine':'検査部',	
'Anesthesiology':'麻酔科',	
'Emergency Medicine':'救急科',	
'Surgery':'外科', 	
'General surgery':'一般外科/総合外科',
'Orthopaedic Surgery':'整形外科',	
'Orthopedics':'整形外科',
'Thoracic Surgery':'呼吸器外科',	
'Spine Surgery':'脊椎外科',
'Neurosurgery':'脳神経外科',	
'Cardiovascular Surgery':'心臓血管外科',
'Vascular':'血管',
'Gastroenterological Surgery':'消化器外科',	
'Esophageal Surgery':'食道外科',	
'Renal Surgery':'腎臓外科',	
'Liver Surgery':'肝臓外科',	
'Endocrine Surgery':'内分泌外科',	
'Hepatobiliary Surgery':'肝胆膵外科',
'Pancreatic Surgery':'肝胆膵外科',	
'Hepatobiliary and Pancreatic Surgery':'肝胆膵外科',
'Head and Neck Surgery':'頭頸部外科',		
'Pediatric Surgery':'小児外科',	
'Pediatrics':'小児科',	
'Oral Surgery':'口腔外科',	
'Urology':'泌尿器科',	
'Nephro-Urological Surgery':'腎泌尿器外科',	
'Cosmetic Surgery':'美容外科', 
'Plastic Surgery':'形成外科',	
'Plastic and Reconstructive Surgery':'形成外科',	
'Immunology':'免疫学',	
'Somnology':'睡眠学',	
'Parasitology':'寄生虫学',	
'Mycology':'真菌学',	
'Virology':'ウイルス学',	
'Acute Medicine':'救急医学'	,
'Occupational Medicine':'産業医学',	
'Biostatistics':'臨床統計学',	
'Anatomical Pathology':'形態機能病理学',	
'Physiology':'生理学',	
'Human Behavior':'行動学',	
'Neuropsychiatry':'精神神経科学',
'Psychiatry':'精神経科',
'Psychological Science':'心理学',	
'Statistical Genetics':'遺伝統計学',
'Anatomy':'解剖学',
'Veterinary':'獣医学',
'Legal Medicine':'法医学',
'Sports Medicine':'スポーツ医学',	
'Environmental Medicine':'環境医学',	
'Forensic Medicine':'法医学',	
'Sleep Medicine':'睡眠医学',	
'Emergency Medicine':'緊急医学',	
'Submarine Medicine':'潜水医学',
'Eastern medicine':'東洋医学', 
'Oriental Medicine':'東洋医学',
'Traditional Chinese Medicine':'東洋医学',
'Ultrasonics':'超音波',
'Nursing':'看護師',
'Nurse':'看護師',
'Pharmacy':'薬剤師',
'Technician':'技師',
'Therapist':'理学療法士',
'Dietician':'管理栄養士'

}